name: Unit Test
# on: pull-request
on: workflow_dispatch
jobs:
  run-main-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"
      - name: "Run main test"
        run: "go test"